/**
 * Official DLD reference vocabularies, extracted from the DLD land/building
 * registration template (DATA sheet dropdown lists). These are the canonical
 * raw registry spellings — use them to validate incoming AREA_EN / type values
 * and to flag any name the importers do not recognize.
 */

export const DLD_COMMUNITIES = [
  "AL Athbah",
  "AL MIZHAR FOURTH",
  "AL QUSAIS",
  "AL TWAR FIFTH",
  "Abu Hail",
  "Al Asbaq",
  "Al Aweer First",
  "Al Aweer Second",
  "Al Baagh",
  "Al Bada",
  "Al Baharna",
  "Al Baraha",
  "Al Barsha",
  "Al Barsha First",
  "Al Barsha Second",
  "Al Barsha South Fifth",
  "Al Barsha South Fourth",
  "Al Barsha Third",
  "Al Barshaa South First",
  "Al Barshaa South Second",
  "Al Barshaa South Third",
  "Al Buteen",
  "Al Dhagaya",
  "Al Eyas",
  "Al Faga'A",
  "Al Fahidi",
  "Al Garhoud",
  "Al Goze First",
  "Al Goze Fourth",
  "Al Goze Industrial First",
  "Al Goze Industrial Fourth",
  "Al Goze Industrial Second",
  "Al Goze Industrial Third",
  "Al Goze Third",
  "Al Hamriya",
  "Al Hamriya Port",
  "Al Hathmah",
  "Al Hebiah Fifth",
  "Al Hebiah First",
  "Al Hebiah Fourth",
  "Al Hebiah Second",
  "Al Hebiah Sixth",
  "Al Hebiah Third",
  "Al Hudaiba",
  "Al Jadaf",
  "Al Jafliya",
  "Al Karama",
  "Al Khabeesi",
  "Al Khairan  Second",
  "Al Khairan First",
  "Al Khawaneej",
  "Al Khawaneej First",
  "Al Khawaneej Second",
  "Al Kheeran",
  "Al Kifaf",
  "Al Layan 2",
  "Al Layan1",
  "Al Lusaily",
  "Al Maha",
  "Al Mamzer",
  "Al Manara",
  "Al Mararr",
  "Al Marmoom",
  "Al Merkadh",
  "Al Meryal",
  "Al Mizhar",
  "Al Mizhar First",
  "Al Mizhar Second",
  "Al Mizhar Third",
  "Al Murqabat",
  "Al Musalla (Dubai)",
  "Al Muteena",
  "Al Nahda First",
  "Al Nahda Second",
  "Al Oshoosh",
  "Al Qoaz",
  "Al Qusais",
  "Al Qusais Industrial Fifth",
  "Al Qusais Industrial First",
  "Al Qusais Industrial Fourth",
  "Al Qusais Industrial Second",
  "Al Qusais Industrial Third",
  "Al Raffa",
  "Al Ras",
  "Al Rashidiya",
  "Al Rega",
  "Al Rowaiyah First",
  "Al Rowaiyah Second",
  "Al Rowaiyah Third",
  "Al Ruwayyah",
  "Al Sabkha",
  "Al Safaa",
  "Al Saffa First",
  "Al Saffa Second",
  "Al Safouh First",
  "Al Safouh Second",
  "Al Sanaiyya",
  "Al Satwa",
  "Al Suq Al Kabeer",
  "Al Thanayah Fourth",
  "Al Thanyah Fifth",
  "Al Thanyah First",
  "Al Thanyah Second",
  "Al Thanyah Third",
  "Al Ttay",
  "Al Twar First",
  "Al Twar Fourth",
  "Al Twar Second",
  "Al Twar Third",
  "Al Waheda",
  "Al Wajehah Al Bhariyah",
  "Al Warqa Fifth",
  "Al Warqa First",
  "Al Warqa Fourth",
  "Al Warqa Second",
  "Al Warqa Third",
  "Al Warsan First",
  "Al Warsan Second",
  "Al Warsan Third",
  "Al Wasl",
  "Al Wohoosh",
  "Al Yelayiss 1",
  "Al Yelayiss 2",
  "Al Yelayiss 3",
  "Al Yelayiss 4",
  "Al Yelayiss 5",
  "Al Yufrah 1",
  "Al Yufrah 2",
  "Al Yufrah 3",
  "Al Yufrah 4",
  "Al Zaroob",
  "Al-Aweer",
  "Al-Baloosh",
  "Al-Bastakiyah",
  "Al-Cornich",
  "Al-Dzahiyyah Al-Jadeedah",
  "Al-Muhaisnah North",
  "Al-Murar Jadeed",
  "Al-Murar Qadeem",
  "Al-Musalla (Deira)",
  "Al-Mustashfa West",
  "Al-Nabgha",
  "Al-Nahdah",
  "Al-Nakhal",
  "Al-Qiyadah",
  "Al-Raulah",
  "Al-Riqqa East",
  "Al-Riqqa West",
  "Al-Safiyyah",
  "Al-Shumaal",
  "Al-Souq Al Kabeer (Deira)",
  "Al-Souq Al-Muqayatah",
  "Al-Tawar",
  "Al-Zarouniyyah",
  "Almarmum First",
  "Almarmum Third",
  "Almeydan",
  "Anakhali",
  "Bukadra",
  "Bur Dubai",
  "Burj Khalifa",
  "Burj Nahar",
  "Business Bay",
  "Cornich Deira",
  "Dubai International Airport",
  "Dubai Investment Park First",
  "Dubai Investment Park Second",
  "Emirates Hills Fourth",
  "Eyal Nasser",
  "Festival City First",
  "Ghadeer Al tair",
  "Ghadeer Barashy",
  "Grayteesah",
  "Hadaeq Sheikh Mohammed Bin Rashid",
  "Hafair",
  "Hatta",
  "Hessyan First",
  "Hessyan Second",
  "Hor Al Anz",
  "Hor Al Anz East",
  "Island 2",
  "Jabal Ali",
  "Jabal Ali First",
  "Jabal Ali Industrial First",
  "Jabal Ali Industrial Second",
  "Jabal Ali Industrial Third",
  "Jabal Ali Second",
  "Jabal Ali Third",
  "Jumeira Island 2",
  "Jumeira Island First",
  "Jumeirah",
  "Jumeirah First",
  "Jumeirah Second",
  "Jumeirah Third",
  "Le Hemaira",
  "Lehbab",
  "Lehbab First",
  "Lehbab Second",
  "Madinat Al Mataar",
  "Madinat Dubai Almelaheyah",
  "Madinat Hind 1",
  "Madinat Hind 2",
  "Madinat Hind 3",
  "Madinat Hind 4",
  "Madinat Latifa",
  "Mankhool",
  "Margham",
  "Marsa Dubai",
  "Me'Aisem First",
  "Me'Aisem Second",
  "Mena Jabal Ali",
  "Mereiyeel",
  "Mirdif",
  "Muashrah Al Bahraana",
  "Mugatrah",
  "Muhaisanah Fifth",
  "Muhaisanah First",
  "Muhaisanah Fourth",
  "Muhaisanah Second",
  "Muhaisanah Third",
  "Muhaisna",
  "Muragab",
  "Mushrif",
  "Nad Al Hamar",
  "Nad Al Shiba",
  "Nad Al Shiba First",
  "Nad Al Shiba Fourth",
  "Nad Al Shiba Second",
  "Nad Al Shiba Third",
  "Nad Rashid",
  "Nad Shamma",
  "Nadd Hessa",
  "Naif",
  "Naif North",
  "Naif South",
  "Nazwah",
  "OUD AL MUTEENA",
  "Oud Al Muteena",
  "Oud Metha",
  "Palm Deira",
  "Palm Jabal Ali",
  "Palm Jumeirah",
  "Port Saeed",
  "Ras Al Khor",
  "Ras Al Khor Industrial First",
  "Ras Al Khor Industrial Second",
  "Ras Al Khor Industrial Third",
  "Rega Al Buteen",
  "Remah",
  "Riqat Masali",
  "Saih Aldahal",
  "Saih Alsalam",
  "Saih Shuaelah",
  "Saih Shuaib 1",
  "Saih Shuaib 2",
  "Saih Shuaib 3",
  "Saih Shuaib 4",
  "Shandagha",
  "Shandagha East",
  "Shandagha West",
  "Sikka Al Khail",
  "Sikkat Al Khail North",
  "Sikkat Al Khail South",
  "Souq Al-Lariyyah",
  "Souq Al-Tamar",
  "Souq Sikkat Al Khail",
  "Tareeq Abu Dhabi",
  "Tareeq Al Aweer",
  "Tawaa Al Sayegh",
  "Tawi Al Muraqqab",
  "Tawi Alfuqa",
  "Trade Center First",
  "Trade Center Second",
  "Um Al Sheif",
  "Um Almoameneen",
  "Um Esalay",
  "Um Hurair First",
  "Um Hurair Second",
  "Um Ramool",
  "Um Suqaim",
  "Um Suqaim First",
  "Um Suqaim Second",
  "Um Suqaim Third",
  "Umm Addamin",
  "Umm Hurair",
  "Universe Islands",
  "Wadi Al Amardi",
  "Wadi Al Safa 2",
  "Wadi Al Safa 3",
  "Wadi Al Safa 4",
  "Wadi Al Safa 5",
  "Wadi Al Safa 6",
  "Wadi Al Safa 7",
  "Warsan Fourth",
  "World Islands",
  "Yaraah",
  "Zaabeel First",
  "Zaabeel Second",
  "Zabeel East",
  "Zareeba Duviya",
] as const;

export const DLD_PROPERTY_TYPES = [
  "ATM",
  "Arabian House",
  "Bank",
  "Building",
  "Building multi-storey parking",
  "Car Wash",
  "Cinema",
  "Clinic",
  "College",
  "Comercial Complex",
  "Complex Villas",
  "Complex Warehouse",
  "Complex markets",
  "Desk",
  "Endowments attached to mosques",
  "Factory",
  "Farm",
  "Flat",
  "GYM",
  "Garage",
  "Hall",
  "Health club",
  "Horse stable",
  "Hospital",
  "Hotel",
  "Hotel apartments",
  "Kiosk",
  "Lab",
  "Labor Camps",
  "Ladies Saloon",
  "Land Parking",
  "Laundry",
  "Medical Store",
  "Medical center",
  "Medical complex",
  "Mezzanine",
  "Nursery",
  "OPEN STORAGE SHED",
  "Office",
  "Open Land",
  "Open space",
  "Parking",
  "Penthouse",
  "Pertol station",
  "Petrol station",
  "Pharmacy",
  "Portacabin",
  "Printing Press",
  "Restaurant",
  "Resturants Complex",
  "School",
  "Service Center",
  "Shop",
  "Shopping Center",
  "Showroom",
  "Sign Board",
  "Spa",
  "Sports Club",
  "Staff Accommodation",
  "Storage",
  "Store",
  "Studio",
  "Supermarket",
  "Supermarket, a multi-section",
  "University",
  "Villa",
  "Villa addendum",
  "Warehouse",
  "Warehouse complex",
  "Workshop",
  "church",
  "hotel building",
  "kitchen",
  "museum",
  "swimming pool",
] as const;

export const DLD_PROPERTY_USAGES = [
  "Commercial",
  "Educational facility",
  "Health Facility",
  "Industrial",
  "Industrial / Commercial",
  "Industrial / Commercial / Residential",
  "Origin Tratij",
  "Residential",
  "Residential / Commercial",
  "Storage",
  "Tourist origin",
] as const;

const _communitySet = new Set(DLD_COMMUNITIES.map((c) => c.toLowerCase().trim()));
/** True if the raw name is a recognized official DLD community. */
export function isKnownCommunity(raw: string): boolean {
  return _communitySet.has((raw || "").toLowerCase().trim());
}
